
language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate

script:
  - vendor/bin/phpunit
  
directories:
    - $HOME/.composer/cache/files
addons:
  sonarqube:
   
 branches:
    - master
    - sonaqube
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner